name: home_service_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  simple_animations: ^5.0.2
  scrollable_positioned_list: ^0.3.8
  flutter_gen: ^5.4.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  build_runner: ^2.4.9
  icons_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/